dist: trusty
language: python
python: 3.6
branches:
  only:
  - sources
sudo: false

env:
  global:
    - secure: "ynaTam1madBRwY/zDo7VDWk8LFxeKUjpO+K+h6fubPZbr+SN3Iiax+gK8q1sHsjzK7T0wdj2tIHEg8XVppbx1Dw7mm822Kpa3PodjkObx0PDpYB7B3yVyaj3EvpSCpi4lTmGUZR4mxN7zCpKgK1A+hxP/RX/ExxZ5WegbK9Tn5RdcWMfIcZpRf7UOuNL8WZWEo6ayqZsDGX/WeB4zKHOZfWgzYinqbcxl5HiHKzFIMIooQxbpI7ZFZgzOjSMCBkdcelOsTMjp9xiGQfr8pi9X9ExLzmfoMlBx31SMfAnqezUquu9iD8cGDzhcwvwzKIo8NjXOCzyLBxsvMFSg3ADKlP2qWAPZ3YPUpWL3EVk6hDa6U0rY/q76cJPr1RTb+8TT/LZIXD1PDBqR6WiOMZKrOQhxYlKhWlEu2OjJThZRtaCSdglEuh+V1ofHPld8J9R42XtGrAn8aA7J1hEvNvukxkf1pyGati8QgsHoq0U2UkC/M8z2gtAaJAGf96PFP/IQu0ukkcSkW/oTeXTGhbQtsmT/N1vHYcDvIMZEde1UkGdje7nmkCLqbzuk1LJe+n5/gms+VaDOEAwquOe2/PquQbwqd6/LQfnhtrLKezQKD8yS7INa1vZC6/iaY3W6TSP1uGaLT03OaaE60MmyNNldw/JCTH4RQP0+zlpEHeUepo="

addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/texlive'
    packages:
    - texlive-full
#    - texlive-xetex
#    - texlive-fonts-recommended
#    - texlive-fonts-extra

install:
- pip install PyYaml jinja2 doctr
- gem install bundler
- bundle install
before_script:
- cd resume
- make html PDF_LINK="{{site.url}}/static_files/cv.pdf" && cp output/cv.html ../_includes/cv.html
- make pdf && mkdir ../static_files && cp output/cv.pdf ../static_files/
- cd ..
script:
- set -e
- bundle exec jekyll build --destination www
- doctr deploy . --built-docs www/ --deploy-branch-name master --no-require-master
