
title: Will Barnes
year: 2017
email: will.t.barnes@gmail.com
description: "Will Barnes is a PhD student in solar physics interested open-source software and scientific computing."
baseurl: "" 
url: "https://wtbarnes.github.io/" 

# Social
twitter_username: wtbarnes_
github_username:  wtbarnes
stack_overflow_username: 4717663/will-barnes

permalink: pretty

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
include: ["_pages","images","static_files"]
exclude:
  - resume/
  - Gemfile
  - Gemfile.lock

